<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Darask.Tools.Bench</RootNamespace>
    <AssemblyName>bench</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Darask.Enumeration\Darask.Enumeration.csproj" />
  </ItemGroup>

</Project>
